apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: cf-pipeline2
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-c2fcdaad-2cdb-4a12-bbe5-e236c37d5438:
      events:
        - push
      repositories:
        - owner: Jukie
          names:
            - test-csdp
      webhook:
        port: '80'
        method: POST
        endpoint: >-
          /webhooks/codefresh-round3/cf-pipeline2/github-c2fcdaad-2cdb-4a12-bbe5-e236c37d5438
        url: https://codefresh-csdp-poc-bolt.net
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
